dist: xenial
language: rust
rust:
  - nightly
  - beta
  - stable
env:
  - GTK=3.14 FEATURES=
  - GTK=3.24 FEATURES=v3_16
addons:
  apt:
    packages:
    - libgtk-3-dev
    - libmount-dev
script:
  - rustc --version
  - mkdir .cargo
  - echo 'paths = ["."]' > .cargo/config
  - git clone -q --depth 50 -b pending https://github.com/gtk-rs/examples _examples
  - cd _examples
  - ./build_travis.sh
